### ISSUE TITLE
Version 6.2.0 - Composant tAdvancedCMISOutput

### ISSUE THREAD

**Issue by vikkooo** [Ekito/talend-cmis-components#34]
Bonjour, 
avez-vous un tutorial pour le composant tAdvancedCMISOutput ? merci

**Comment by FredFromBordeaux** [comment]
Bonjour, 
Avez-vous utilisez ce composant sur la verison Talend v6.2 ?
ou sur une version antérieur ? 

(la solution pour la verison 6.0 ne fonctionne pas :s)

Merci
Frédéric de Bordeaux

**Comment by julienboulay** [comment]
Bonjour Frédéric,

Les composants cmis ne fonctionnent pas avec Talend v6, car les plugins
n'ont pas été mis à jour avec cette dernière version.
Le code source est disponible et votre contribution est la bienvenue.
Cordialement

Le 20 sept. 2016 03:12, "FredFromBordeaux" notifications@github.com a
écrit :

Bonjour,
Avez-vous utilisez ce composant sur la verison Talend v6.2 ?
ou sur une version antérieur ?

Merci
Frédéric de Bordeaux

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/Ekito/talend-cmis-components/issues/34#issuecomment-248074221,
or mute the thread

**Comment by FredFromBordeaux** [comment]
Bonjour Julien, 
aaahh j'ai beaucoup oublié en java et manipulation de Eclipse ! .... c'est toujours un moyen de s'y remettre ... mais là, je fais "appel à un ami ! "
et sous Talend, je n'ai pas encore développé de Composant ... bon, ok là aussi c'est une bonne occasion ...

Sous Talend, j'ai supprimé le répertoire :
"org.talend.libraries.apache.chemistry_6.2.1.20160704_1411"
et cela fonction trés bien (pour CMISInput déjà) ! 

Par contre, j'ai toujours une erreur, 
à l'ouverture de la fenetre "Object type" dans CMISInput, et Editor dans "CMISOutput" :
java.lang.NoClassDefFoundError: org/talend/core/ui/images/CoreImageProvider
    at org.talend.designer.cmis.ui.EditorDialog.configureShell(EditorDialog.java:160)
    at org.eclipse.jface.window.Window.createShell(Window.java:507)
    at org.eclipse.jface.window.Window.create(Window.java:434)
    at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1101)

as tu une idée ? 
Frédéric

**Comment by FredFromBordeaux** [comment]
Bonjour Julien, 
Je suis arrivé à l'étape suivante ! 
Par contre, pour le module TAdvancedCMISOutput, j'ai des soucis ! 
tu aurais pas un exemple ? 
ça serait super ! 
Frédéric 
ps : ca vaudra bien un petit St Emilion, ou un Pessac Leognan à déguster ...

**Comment by julienboulay** [comment]
Salut Fred,

Je reprends le boulot aujourd'hui après 15 jours de congés.
Qu'entends tu par "arriver à l'étape suivante" ?
Je n'ai pas fait fonctionner les composants sur Talend V6, car je n'ai pas
d'environnement de développement à jour avec cette version.
Dis-moi si je peux t'aider sur quoi que ce soit.
A bientôt

Julien

_Julien Boulay_ _\- Ekito_
Developer & Eclectic
15 rue Gabriel Péri 31000 Toulouse
+33 (0)6 80 46 73 78
jboulay@ekito.fr
_Visit our Blog http://www.ekito.fr/people !_

Le 26 septembre 2016 à 20:19, FredFromBordeaux notifications@github.com a
écrit :

**Comment by FredFromBordeaux** [comment]
Bonjour Julien, 
et je commence 1 semaine de congés à mon tour ... j'ai donc le temps d'avancer ce sujet ...
désolé j'ai fait court dans mon message précédent.
Donc, je n'arrivais pas à ouvrir la fenetre "Object type" dans CMISInput, et Editor dans "CMISOutput" :
java.lang.NoClassDefFoundError: org/talend/core/ui/images/CoreImageProvider

J'ai repris Eclipse, nouvelle compilation de talend-cmis-plugins en jar et hop ça marche !  Miracle ! 
Donc le module TCMISInput fonctionne très bien !

Pour le module tCMISOutput, j'ai juste un petit problème : je souhaite mettre à jour les propriétés d'un document déjà existant, mais je pense que je dois renseigné le paramètre "path" ; 
est-ce que je dois renseigner ce paramètre à chaque fois ? même si je ne veux seulement mettre à jour les propriétés ? 

voila voila , c'est certainement tout bête , mais je vois pas :p
Frédéric

**Comment by julienboulay** [comment]
Bonjour Fred,

Je suis désolé, mais je n'ai pas touché à ces composants depuis au moins 2
ans et je ne me souviens pas du tout comment procéder à la mise à jour des
propriétés.
D'ailleurs, je ne suis pas sûr d'avoir pris en charge la mise à jour dans
cette version qui est restée expérimentale.
Il faudrait jeter un coup d'oeil au code "javajet" et à l'api pour voir ce
qui est fait dans le code, mais je n'ai malheureusement pas le temps de me
pencher dessus...
Bon courage
Cordialement

Julien

_Julien Boulay_ _\- Ekito_
Developer & Eclectic
15 rue Gabriel Péri 31000 Toulouse
+33 (0)6 80 46 73 78
jboulay@ekito.fr
_Visit our Blog http://www.ekito.fr/people !_

Le 6 octobre 2016 à 11:21, FredFromBordeaux notifications@github.com a
écrit :
