### ISSUE TITLE
Boolean, Decimal, Integer properties generate ClassCastException

### ISSUE THREAD

**Issue by julienboulay** [Ekito/talend-cmis-components#7]
Exception in component tAdvancedCMISInput_1
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
    at cmis.tcmisinput_read_document_0_1.tCMISInput_read_document.tAdvancedCMISInput_1Process(tCMISInput_read_document.java:797)
    at cmis.tcmisinput_read_document_0_1.tCMISInput_read_document.runJobInTOS(tCMISInput_read_document.java:1240)
    at cmis.tcmisinput_read_document_0_1.tCMISInput_read_document.main(tCMISInput_read_document.java:1108)

**Comment by julienboulay** [comment]
Boolean, Decimal, Integer and Date properties were not managed properly.
Fixed by 359f0b6a5c25d4ea2e7a60b966af771fb0b98c1f  and 191ef6addb7afa753632bb4359f87beb3d375273
